import { HeartHandshake, MessagesSquare, FileSearch, House, Wallet, Users, BookOpen, ClipboardList } from 'lucide-react';
import {content,links,faq,type Audience} from './content';
import {Questions} from './faq';
function Actions({audience,materials=false,choose=false}:{audience:Audience;materials?:boolean;choose?:boolean}){return <div className="actions">{choose?<><a className="btn" href="/men">Хочу жену</a><a className="btn secondary" href="/women">Хочу мужа</a></>:<a className="btn" href={materials?links.materials:links.profile}>{materials?'Получить вопросы и тест':'Оставить анкету бесплатно'}</a>}</div>}
function Brand(){return <a className="brand" href="/"><img src="/brand.jpg" alt="" width="52" height="52"/>Линара женит</a>}
export function Landing({audience='home'}:{audience?:Audience}){const d=content[audience];return <>
<a className="skip" href="#main">Перейти к содержанию</a>
<div className={'hero '+audience}><img className="hero-photo" src={'/'+d.image} alt="" fetchPriority="high" width="1536" height="1024"/><header><div className="wrap nav"><Brand/><nav className="nav-links" aria-label="Основная навигация"><a href="/#about">Об агентстве</a>{audience!=='men'&&<a href="/men">Для мужчин</a>}{audience!=='women'&&<a href="/women">Для женщин</a>}<a href="#questions">Вопросы</a></nav></div></header><div className="wrap hero-content"><div className="hero-copy"><span className="eyebrow">{audience==='home'?'Знакомства для никаха':'Брачное агентство «Линара женит»'}</span><h1>{d.title}</h1><p>{d.intro}</p><Actions audience={audience} choose={audience==='home'}/></div></div></div>
<main id="main">
<section className="section"><div className="wrap split"><div><h2>{d.pain}</h2>{d.paragraphs.map(p=><p key={p}>{p}</p>)}</div><div className="quotes">{d.quotes.map(q=><blockquote key={q}>{q}</blockquote>)}</div></div></section>
{audience==='home'?<section className="section dark" id="about"><div className="wrap"><h2>Поможем познакомиться<br/>и разобраться в выборе</h2><p className="narrow">В «Линара женит» можно посмотреть анкеты людей, которые ищут супруга, рассказать о себе и получить помощь с дальнейшим знакомством.</p><div className="grid">{[{I:HeartHandshake,t:'Найти, с кем познакомиться',p:'Оставьте свою анкету и посмотрите анкеты других. Если хотите поручить поиск агентству, с менеджером можно обсудить подбор под ваши пожелания.'},{I:MessagesSquare,t:'Начать общение',p:'Менеджер помогает организовать знакомство и первый разговор с семьёй, согласовать общение с участием вали.'},{I:FileSearch,t:'Узнать больше до решения',p:'Вопросы до никаха помогут обсудить ожидания от брака. Если нужно уточнить сведения о человеке, можно заказать проверку по открытым источникам.'}].map(({I,t,p})=><article key={t}><span className="icon"><I aria-hidden="true"/></span><h3>{t}</h3><p>{p}</p></article>)}</div><p>Начните с бесплатной анкеты. Дополнительную помощь и её условия обсудите с менеджером.</p><Actions audience={audience}/></div></section>:<section className="section" id="about"><div className="wrap narrow"><span className="icon"><HeartHandshake aria-hidden="true"/></span><h2>{audience==='men'?'Начните с тех, кто тоже ищет супруга':'Вы можете знакомиться и узнавать человека до решения'}</h2><p>{audience==='men'?'Посмотрите анкеты женщин и расскажите о себе: как вы живёте, что для вас важно в вере и отношениях, какую семью хотите создать.':'Посмотрите анкеты мужчин и расскажите о себе. Менеджер поможет организовать первое общение, вопросы до никаха — обсудить ожидания от брака. Если нужно уточнить сведения о человеке, можно обсудить проверку.'}</p><p>Публикация простой анкеты в наших соцсетях и просмотр анкет бесплатны. С дальнейшим знакомством поможет менеджер. Если хотите поручить поиск агентству, обсудите подбор под ваши пожелания.</p><Actions audience={audience}/></div></section>}
{audience==='home'&&<section className="section center"><div className="wrap"><div className="narrow"><h2>Расскажите о себе тем,<br/>кто тоже хочет семью</h2><p>Как вы живёте? Что для вас важно в вере и отношениях? Какого супруга хотите встретить?</p><p>В анкете можно рассказать о том, что трудно понять по одному фото. Другим людям будет проще увидеть ваши ожидания, а вам — сравнить их со своими.</p><p>Публикация простой анкеты в наших соцсетях бесплатная. Смотреть анкеты мужчин и женщин тоже можно бесплатно.</p><Actions audience={audience}/></div></div></section>}
{audience!=='home'&&<section className="section dark"><div className="wrap"><h2>{audience==='women'?'Что стоит узнать о мужчине до никаха':'Как понять, подойдёте ли вы друг другу'}</h2><div className="topics">{[House,Wallet,BookOpen,Users].map((I,i)=><article key={i}><span className="icon"><I aria-hidden="true"/></span><h3>{(audience==='women'?['Где будете жить','Деньги и обязательства','Работа и дети','Отношения с семьёй']:['Дом и быт','Деньги и работа','Вера и ценности','Дети и семья'])[i]}</h3></article>)}</div><p className="narrow">{audience==='women'?'Где он собирается жить? Есть ли у него долги? Как относится к вашей работе? Чего ждёт от жены и что готов брать на себя?':'По фотографии и приятной переписке трудно понять, как вы будете жить вместе. Обсудите жильё, обязанности и ожидания от брака. Посмотрите, можете ли вы говорить о разногласиях.'}</p><p className="narrow">Часть вопросов стоит обсудить друг с другом. Какие сведения можно проверить по открытым источникам, объяснит менеджер. Проверка помогает узнать факты, но не предсказывает характер и поведение после свадьбы.</p></div></section>}
<section className="section" id="materials"><div className="wrap split"><div className="guides" aria-hidden="true"><div className="guide"><small>Линара женит</small><strong><span className="number">20</span><br/>вопросов<br/>до никаха</strong><BookOpen/></div><div className="guide"><small>Линара женит</small><strong>Матрица<br/>совмести&shy;мости</strong><ClipboardList/></div></div><div><h2>{audience==='women'?'О чём спросить будущего мужа, даже если неловко':audience==='men'?'Что спросить у будущей жены до никаха':'Что стоит обсудить до никаха'}</h2><p>{audience==='home'?'«Будем жить дружно» каждый понимает по-своему. А где именно жить, кто оплачивает расходы и как часто приезжают родители — это уже конкретные вопросы.':audience==='men'?'Будет ли она работать после свадьбы? Готова ли к переезду? Как вы оба представляете воспитание детей и распределение обязанностей? Обсудите это до решения о браке.':'«Где мы будем жить после никаха и с кем?» «Как ты относишься к работе жены?» «Кто в твоей семье принимает решения?» Ответы влияют на вашу будущую жизнь — стоит поговорить о них заранее.'}</p><h3>Двадцать вопросов, которые задают до никаха</h3><p>В материале собраны темы о вере, намерениях, деньгах, детях и быте. К вопросам есть пояснения, что стоит обсудить подробнее.</p>{audience==='home'&&<ul><li>Где мы будем жить после никаха и с кем?</li><li>Как вы видите распределение расходов?</li><li>Какую роль родители будут играть в нашей семейной жизни?</li></ul>}<h3>Тест «Матрица совместимости»</h3><p>Поможет сравнить ваши взгляды и заметить разногласия, к которым стоит вернуться в разговоре.</p><p>Оба материала получите бесплатно после заполнения анкеты.</p><Actions audience={audience} materials/></div></div></section>
{audience!=='home'&&<section className="section"><div className="wrap split"><div><h2>{audience==='men'?'Первый разговор с её семьёй не нужно придумывать самому':'Первое общение можно организовать через менеджера'}</h2><p>{audience==='men'?'«Что сказать её отцу? Как представиться? Когда говорить о своих намерениях?»':'Не знаете, как начать разговор, стесняетесь сразу говорить о никахе или хотите обсудить участие вали?'}</p><p>Менеджер поможет организовать знакомство и первый разговор с семьёй. Какую помощь вы хотите получить и на каких условиях, обсудите заранее.</p>{audience==='women'&&<p>Если у вас нет вали, расскажите об этом менеджеру: вашу ситуацию обсудите отдельно.</p>}</div><MessagesSquare className="conversation-icon" aria-hidden="true"/></div></section>}
{audience==='women'&&<section className="section"><div className="wrap narrow"><h2>«А если я с ребёнком, после развода или мне больше сорока?»</h2><p>Вы можете оставить анкету, если были в браке, потеряли супруга или воспитываете детей. Расскажите о себе, своих пожеланиях и о том, с чем вы не готовы мириться.</p><p>Ваш опыт и обстоятельства важны для выбора человека, с которым вы хотите строить семью.</p></div></section>}
<section className="section" id="questions"><div className="wrap"><h2 className="center">Вопросы {audience==='men'?'о поиске жены':audience==='women'?'о поиске мужа':'о знакомстве через агентство'}</h2><Questions items={faq[audience]}/></div></section>
<section className="section"><div className="wrap split"><h2>Познакомьтесь<br/>с «Линара женит»</h2><div><p>В наших сообществах публикуются анкеты и материалы о выборе супруга. Посмотрите, о чём мы говорим и как помогаем подготовиться к знакомству.</p><div className="socials"><a href={links.vk}>ВКонтакте ↗</a><a href={links.telegram}>Telegram ↗</a></div></div></div></section>
<section className="section dark center"><div className="wrap narrow"><h2>{audience==='home'?'Начните с человека, которого ищете':audience==='men'?'Расскажите о себе женщине, которая тоже ищет мужа':'Начните знакомиться с теми, кто тоже хочет семью'}</h2><p>Оставьте анкету в наших соцсетях бесплатно и посмотрите анкеты тех, кто тоже хочет создать семью. Вопросы до никаха помогут подготовиться к знакомству, а с дальнейшими шагами поможет менеджер.</p><Actions audience={audience} choose={audience==='home'}/></div></section>
</main><footer><div className="wrap"><Brand/><div className="socials"><a href={links.vk}>ВКонтакте</a><a href={links.telegram}>Telegram</a></div></div></footer></>}

